# Form implementation generated from reading ui file 'ui/StatisticsDialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.Tracker = QtWidgets.QPushButton(Dialog)
        self.Tracker.setGeometry(QtCore.QRect(150, 70, 93, 28))
        self.Tracker.setObjectName("Tracker")
        self.DHT = QtWidgets.QPushButton(Dialog)
        self.DHT.setGeometry(QtCore.QRect(150, 120, 93, 28))
        self.DHT.setObjectName("DHT")
        self.BT = QtWidgets.QPushButton(Dialog)
        self.BT.setGeometry(QtCore.QRect(150, 170, 93, 28))
        self.BT.setObjectName("BT")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Tracker.setText(_translate("Dialog", "Tracker"))
        self.DHT.setText(_translate("Dialog", "DHT"))
        self.BT.setText(_translate("Dialog", "Bittorrent"))
